theme: jekyll-theme-minimal
title: Cameron Allen Portfolio
description: A portfolio of my work.
show_downloads: True
navigation:
  - title: Home
    url: projects
  - title: Projects
    url: projects
